const $=x=>document.getElementById(x),E={q:$('q'),rec:$('rec'),gen:$('gen'),status:$('status'),ls:$('ls'),title:$('title'),lat:$('lat'),out:$('out'),empty:$('empty'),aa:$('aa'),style:$('style'),ultra:$('ultra'),live:$('live'),liveText:$('liveText'),end:$('end'),modal:$('modal'),close:$('close'),startU:$('startU'),copy:$('copy'),newq:$('newq'),clear:$('clear'),count:$('count')};
let KB=null,R,on=0,busy=0,fin='',cur=null,timer,restart;let U={active:false,turns:[]};
const A=(say,ex='',ctx='',follow='')=>({say,ex,ctx,follow});
const N=s=>String(s||'').toLowerCase().replace(/[^a-z0-9+#. ]+/g,' ').replace(/\s+/g,' ').trim().replace(/\braag(s)?\b|\brack\b/g,'rag').replace(/\bfine tuning\b/g,'fine-tuning').replace(/\boops\b/g,'oop');
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),hi=s=>esc(s).replace(/==([^=]+)==/g,'<mark>$1</mark>');
async function loadKB(){KB=await fetch('/data/context.json',{cache:'no-store'}).then(r=>r.json())}
function local(q){let n=N(q),h=(...x)=>x.some(k=>n.includes(k)),all=(a,b)=>n.includes(a)&&n.includes(b);
if(h('tell me about yourself','introduce yourself'))return A(`I’m a final-year Computer Science student with strong foundations in ==Java, Python, DSA, OOP, DBMS, SQL, APIs and full-stack development==. I’ve also worked with AI-enabled and data-driven projects, which made me interested in using technology to solve real business problems. That is why this Deloitte ET&P Finance Transformation role appeals to me — it combines structured problem solving, technology, analytics and cross-functional work.`,`Keep this around 60–90 seconds. If they ask for evidence, move into one verified project and explain the problem, your contribution and business value.`,`The FT GBS JD emphasizes business problem understanding, transformation, analytics, project delivery and communication.`,`Likely follow-up: Why Finance Transformation if you are from CSE?`);
if(h('why deloitte'))return A(`I’m interested in Deloitte because it lets me work at the intersection of ==technology and business transformation==. This role involves understanding client problems, analyzing requirements, working across teams and helping implement better processes and solutions. That matches how I want to grow — using technology, data and automation to create measurable business value.`,`Avoid generic brand praise. Connect Deloitte directly to client problems, project delivery, analytics, communication and transformation.`,`The official FT GBS JD stresses client objectives, stakeholder alignment, cross-functional collaboration and project delivery.`,`Likely follow-up: Why this role specifically?`);
if(h('why finance transformation','why ft gbs','why gbs'))return A(`Finance Transformation interests me because it is about ==improving how finance operates using better processes, data, automation and technology==. My CSE background gives me a technical way of looking at inefficiencies, systems and data, while this role lets me apply that thinking to larger business processes and client problems.`,`Example: manual invoice entry and reconciliation can be standardized, automated, integrated with systems and surfaced through dashboards for better visibility.`,`Position yourself as technology + analytics + automation applied to enterprise finance processes, not as an accounting specialist.`,`Likely follow-up: Give me an example of a finance process you would transform.`);
if(h('why consulting'))return A(`Consulting appeals to me because I like ==solving different problems, understanding requirements quickly and working across functions==. It would let me apply my technical background to real organizational problems while learning how business decisions, processes and technology come together.`,`Emphasize variety of problems, structured thinking, communication, teamwork and outcomes.`,`This maps to the JD’s client delivery, stakeholder management, analysis and collaboration.`,`Likely follow-up: How would you handle an ambiguous client problem?`);
if(h('finance transformation'))return A(`Finance Transformation means ==redesigning finance processes, systems, data and operating models to make them faster, more accurate, automated and decision-friendly==.`,`A typical flow is: understand the current process → identify inefficiencies → redesign → introduce technology/automation/data → measure improvement.`,`For Deloitte FT GBS, connect it to business value, project delivery, stakeholder alignment and continuous improvement.`,`Likely follow-up: What technologies can enable finance transformation?`);
if(h('global business services',' gbs '))return A(`GBS is a model where organizations ==standardize and centralize common business processes across functions, regions or business units== to improve efficiency, governance, service quality and automation.`,`The idea is to move from fragmented local processes to shared services, common systems, automation, analytics and continuous improvement.`,`Use the full expansion cautiously because the source notes that GBS appears in the JD while the expansion was discussed rather than explicitly spelled out there.`,`Likely follow-up: How is GBS different from outsourcing?`);
if(h('why should we hire'))return A(`You should hire me because I bring ==strong technical fundamentals, hands-on project experience, fast learning and analytical problem solving==. I can understand systems technically, but I’m also interested in translating requirements into practical solutions and outcomes, which fits a transformation role.`,`Back this with one verified project or challenge if asked for proof. Do not claim client-facing or ERP experience unless true.`,`The JD values initiative, independent learning, communication, requirements analysis and project delivery.`,`Likely follow-up: Give me one example that proves this.`);
if(h('cse','computer science')&&h('finance','transformation'))return A(`My CSE background is useful here because Finance Transformation increasingly depends on ==data, automation, systems integration, analytics and digital platforms==. I’m not approaching it as an accounting specialist; I’m approaching it as a technologist who can understand a process, identify inefficiencies and help design a better data- and technology-enabled solution.`,`This is the safest bridge between your background and the role.`,`Do not claim ERP or professional finance-transformation experience unless confirmed.`,`Likely follow-up: Which technical skill of yours is most useful here?`);
if(h('commercialiq')){let p=KB?.projects?.CommercialIQ;return A(`CommercialIQ is an ==AI-powered commercial decision intelligence platform== that combines forecasting, customer segmentation, predictive risk, analytics, RAG and tool-based AI decision support.`,`Its stack includes React/Vite, Vercel serverless functions, Node.js, Python with Pandas/NumPy/Scikit-learn, and Supabase PostgreSQL. The ML layer covers forecasting, risk classification and RFM/K-Means segmentation, while the AI analyst can use retrieval and analytical tools with deterministic fallback.`,`This is highly relevant to Deloitte FT GBS because it connects analytics, automation, AI governance and business decision support rather than treating ML as an isolated model.`,`Likely follow-up: Explain the architecture or how you validate model outputs.`)}
if(h('skylark'))return A(`Skylark Command is a ==trust-native executive decision intelligence platform over live CRM and operational data==. It combines deterministic analytics, historical change intelligence, Customer 360, Scenario Lab and bounded AI interpretation.`,`The stack uses Next.js, React, TypeScript, Zod, monday.com GraphQL, PostgreSQL, Supabase Auth, Gemini and Vercel. The key design choice is that TypeScript owns business arithmetic; AI can plan or explain, but does not silently create business facts.`,`For Deloitte, it demonstrates enterprise integration, data quality, explainability, stakeholder-facing analytics and transformation-oriented decision support.`,`Likely follow-up: Why did you separate deterministic facts from AI interpretation?`);
if(h('koshora','personal finance'))return A(`Koshora is a ==production-minded personal-finance workspace== connecting transactions, budgets, recurring commitments, accounts and savings goals with deterministic forecasting and explainable insights.`,`It uses Next.js, React, TypeScript, Supabase Auth, PostgreSQL and Row Level Security. The public recruiter demo is frictionless, while the private workspace uses authenticated persistence and membership + ownership authorization.`,`It is relevant to Finance Transformation because it shows finance-domain data modeling, explainable calculations, security and workflow design.`,`Likely follow-up: Why use deterministic forecasting instead of branding it as AI?`);
if(h('acid'))return A(`ACID stands for ==Atomicity, Consistency, Isolation and Durability==. These properties make database transactions reliable.`,`Atomicity is all-or-nothing; consistency preserves rules; isolation controls concurrent transactions; durability keeps committed data after failures.`,`A finance example is a money transfer: debit and credit should complete as one reliable transaction.`,`Likely follow-up: What happens if a transaction fails halfway?`);
if(h('normalization','1nf','2nf','3nf'))return A(`Normalization means ==organizing relational data to reduce redundancy and update anomalies==.`,`1NF keeps values atomic, 2NF removes partial dependency and 3NF removes transitive dependency.`,`Business systems benefit from consistent master and transaction data, while analytics may sometimes denormalize for speed.`,`Likely follow-up: When would you denormalize?`);
if(h('join','sql join'))return A(`A SQL JOIN combines rows from related tables. Common types are ==INNER, LEFT, RIGHT and FULL OUTER JOIN==.`,`INNER returns matches; LEFT keeps all left rows plus matches; RIGHT is the opposite; FULL keeps rows from both sides where supported.`,`Finance systems often join transactions with customer, vendor or account master data.`,`Likely follow-up: WHERE vs HAVING?`);
if(all('where','having'))return A(`WHERE filters rows ==before grouping==, while HAVING filters groups ==after GROUP BY==.`,`Use WHERE for row conditions and HAVING for aggregate conditions such as COUNT, SUM or AVG.`,`This is a common SQL interview distinction.`,`Likely follow-up: Write a query using GROUP BY and HAVING.`);
if(h('abstraction')&&h('interface'))return A(`Abstraction is the principle of ==hiding implementation details and exposing essential behavior==, while an interface defines a contract that implementing classes follow.`,`In Java, abstract classes can hold state/shared implementation; interfaces are useful for loose coupling and multiple capability contracts.`,`Interfaces help enterprise systems stay modular and interchangeable.`,`Likely follow-up: Abstract class vs interface?`);
if(h('polymorphism'))return A(`Polymorphism means ==one parent type or interface can represent multiple concrete implementations==.`,`In Java, runtime polymorphism happens through method overriding.`,`It helps build extensible systems where callers depend on abstractions rather than concrete classes.`,`Likely follow-up: Overloading vs overriding?`);
if(h('rest','rest api'))return A(`A REST API exposes resources over HTTP using ==GET, POST, PUT/PATCH and DELETE==.`,`REST APIs are usually stateless, use resource-oriented URLs and status codes, and commonly exchange JSON.`,`In transformation work, APIs help integrate systems and automate data flows.`,`Likely follow-up: What does stateless mean?`);
if(h('linear search'))return A(`Linear search has ==O(n) worst-case time and O(1) auxiliary space==.`,`It checks items one by one. Best case is O(1) if the first item matches.`,`Coding is not explicitly required by this FT GBS JD, so keep DSA answers crisp unless they go deeper.`,`Likely follow-up: How is binary search different?`);
if(h('binary search'))return A(`Binary search runs in ==O(log n) time== on sorted data, with O(1) auxiliary space iteratively.`,`Every comparison removes half of the remaining search range.`,`Keep defensive DSA knowledge concise unless the panel turns technical.`,`Likely follow-up: Why does it require sorted data?`);
if(h('two sum'))return A(`For Two Sum, the optimized approach uses a ==HashMap for O(n) average time and O(n) space==.`,`For each x, check whether target-x was seen; if yes return the pair, otherwise store x.`,`If asked to code, explain the approach clearly and give complexity.`,`Likely follow-up: Can you do it without extra space?`);
if(all('rag','fine-tuning'))return A(`==RAG changes what information the model sees at query time, while fine-tuning changes the model itself== by updating parameters.`,`RAG suits changing/private knowledge; fine-tuning suits consistent behavior, style or task patterns.`,`Do not turn conceptual knowledge into a claim of implementation.`,`Likely follow-up: Which would you choose for company policy documents?`);
if(h('rag','retrieval augmented'))return A(`RAG lets an LLM ==retrieve relevant external information and use it as context before answering==.`,`It is useful when information is current, private, large or frequently changing.`,`CommercialIQ does include a RAG-style retrieval layer, but describe only the implementation you can personally defend.`,`Likely follow-up: RAG vs fine-tuning?`);
if(h('excel'))return A(`For this role, Excel is useful for ==data cleaning, analysis, reconciliation, summaries and business reporting==.`,`Common skills include formulas, sorting/filtering, PivotTables, lookup functions and charts.`,`The JD explicitly lists Excel, PowerPoint, Visio and Word; only claim the functions you genuinely know.`,`Likely follow-up: Which Excel functions have you used?`);
if(h('stakeholder'))return A(`Stakeholder management means ==identifying affected people, understanding expectations, communicating clearly and keeping everyone aligned around decisions and delivery==.`,`In practice: map stakeholders, clarify roles, communicate progress/risks, handle priorities and document decisions.`,`Your profile lists stakeholder management, but the source-of-truth does not contain a verified real stakeholder story, so do not invent one.`,`Likely follow-up: Tell me about a difficult stakeholder.`);
return null}
function render(a,kind){let h=`<div class="box say"><span class="tag">SAY THIS</span><p>${hi(a.say)}</p></div>`;if(a.ctx)h+=`<div class="box green"><span class="tag">DELOITTE CONTEXT</span><p>${hi(a.ctx)}</p></div>`;if(E.style.value!=='Rapid'&&a.ex)h+=`<div class="box"><span class="tag">EXPLANATION</span><p>${hi(a.ex)}</p></div>`;if(a.follow)h+=`<div class="box"><span class="tag">FOLLOW-UP READY</span><p>${hi(a.follow)}</p></div>`;E.out.innerHTML=h;E.out.classList.add('show');E.empty.style.display='none';E.aa.classList.add('show');E.lat.textContent=kind}
async function ai(q){let r=await fetch('/api/answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,style:E.style.value,session:U.turns.slice(-24)})});if(!r.ok)throw 0;return r.json()}
async function answer(forced=''){let q=(forced||E.q.value).trim();if(!q||busy)return;busy=1;let t=performance.now();E.title.textContent='Generating…';E.status.textContent='Thinking';try{cur=local(q);let kind='instant';if(!cur){try{let x=await ai(q);cur=A(x.say,x.explanation||'',x.deloitteContext||'',x.followUp||'');kind='AI'}catch{cur=A(`I can answer this safely at a high level, but ==the exact recruiter-ready answer is not in the built-in Deloitte pack yet==. Ask the key term in one clear sentence.`,`This dedicated version avoids inventing personal experience or unsupported project details.`,`When relevant, anchor the answer to FT GBS: business problem understanding, analytics, transformation, requirements, project delivery and communication.`,`For project questions, use only implementation details you genuinely built.`);kind='safe'}}render(cur,Math.max(1,Math.round(performance.now()-t))+' ms · '+kind);E.title.textContent='Deloitte-ready answer';E.status.textContent=U.active?'Ultra listening':'Ready'}finally{busy=0;if(U.active&&!on){clearTimeout(restart);restart=setTimeout(startMic,300)}}}
function qlike(s){let n=N(s);return /^(what|why|how|when|where|who|which|can|could|would|should|do|does|did|is|are|tell me|explain|describe|compare|difference|write|implement|solve|walk me|talk about)/.test(n)||/difference between|complexity|what is|how do|your experience/.test(n)}
function listening(v){on=v;E.rec.classList.toggle('on',v);E.rec.textContent=v?'■ Stop Listening':'🎙 Start Listening';E.ls.textContent=v?'● Listening…':'';E.status.textContent=v?(U.active?'Ultra listening':'Listening'):(U.active?'Ultra reconnecting':'Ready')}
function build(){let S=window.SpeechRecognition||window.webkitSpeechRecognition;if(!S)return null;let r=new S;r.continuous=false;r.interimResults=true;r.lang='en-IN';r.onstart=()=>listening(1);r.onresult=e=>{let inter='',final='';for(let i=e.resultIndex;i<e.results.length;i++){let x=e.results[i][0].transcript.trim();if(e.results[i].isFinal)final+=' '+x;else inter+=' '+x}if(U.active){if(final.trim()){let s=final.trim();U.turns.push(s);if(U.turns.length>160)U.turns.shift();E.count.textContent=`${U.turns.length} speech turns remembered`;E.q.value=s;clearTimeout(timer);timer=setTimeout(()=>qlike(s)?answer(s):E.title.textContent='Listening to interview context',600)}else if(inter.trim())E.q.value=inter.trim()}else{fin=(fin+' '+final).trim();E.q.value=(fin+' '+inter).trim();if(final.trim()){clearTimeout(timer);timer=setTimeout(()=>answer(E.q.value),250)}}};r.onerror=e=>{listening(0);if(U.active&&!['not-allowed','service-not-allowed'].includes(e.error)){clearTimeout(restart);restart=setTimeout(startMic,600)}};r.onend=()=>{listening(0);if(U.active){clearTimeout(restart);restart=setTimeout(startMic,300)}};return r}
function startMic(){if(busy)return;if(!R)R=build();if(!R)return alert('Speech recognition is unavailable here. Type the question instead.');try{R.start()}catch{R=build();try{R.start()}catch{listening(0)}}}
function stopMic(){try{R?.stop()}catch{}listening(0)}
function startUltra(){U={active:true,turns:[]};E.ultra.classList.add('on');E.ultra.textContent='⚡ ULTRA SESSION ON';E.live.classList.add('show');E.liveText.textContent='Built-in Deloitte/JD/profile context loaded. Listening auto-restarts during the active page session.';E.modal.classList.remove('show');startMic()}
function endUltra(){U.active=false;clearTimeout(restart);stopMic();E.ultra.classList.remove('on');E.ultra.textContent='⚡ START ULTRA SESSION';E.live.classList.remove('show');E.status.textContent='Ready'}
E.rec.onclick=()=>on?stopMic():startMic();E.gen.onclick=()=>answer();E.clear.onclick=()=>{E.q.value='';fin=''};E.copy.onclick=()=>navigator.clipboard?.writeText((cur?.say||'').replace(/==/g,''));E.newq.onclick=()=>{E.q.value='';fin='';cur=null;E.out.classList.remove('show');E.aa.classList.remove('show');E.empty.style.display='block';E.title.textContent='Waiting for a question';E.lat.textContent='—'};E.ultra.onclick=()=>E.modal.classList.add('show');E.close.onclick=()=>E.modal.classList.remove('show');E.startU.onclick=startUltra;E.end.onclick=endUltra;E.modal.onclick=e=>{if(e.target===E.modal)E.modal.classList.remove('show')};loadKB().catch(()=>{});R=build();